
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ctypes.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "Class2.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "U2ctypes.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE U2ctypes
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\u2ctypes.sdl",15,9)
******/
XCONST struct xPackageIdStruct yPacR_z_U2ctypes__U2ctypes = {xPackageEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "U2ctypes" xIdNumber(0)
  XCOMMON_EXTRAS xIdNames(0) XPAC_EXTRAS};

/*****
* GENERATOR CArray  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",299,11)
******/

/*****
* GENERATOR Ref  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\CPointer.pr",13,11)
******/

/*****
* SYNTYPE int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",13,9)
******/
#ifndef XTNOUSE_int
tSDLGenInfo ySDL_z_U2ctypes_Y0_int = {type_SDL_Syntype, 0,
  (xptrint)sizeof(z_U2ctypes_Y0_int) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("int") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y0_int), (tSDLTypeInfo *)&ySDL_SDL_Integer};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y0_int = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes, "int" xIdNumber(0)
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_Y0_int), xSyntype, &xSrtR_SDL_Integer,
  &xSrtR_SDL_Integer, 0, 0, 0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y0_int)
  XSRT_EXTRAS};
#endif

/*****
* SYNTYPE unsigned_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",21,9)
******/
#ifndef XTNOUSE_unsigned_int
tSDLTypeInfo ySDL_z_U2ctypes_Y1_unsigned_int = {type_SDL_UnsignedInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y1_unsigned_int) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("unsigned_int")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y1_unsigned_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y1_unsigned_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "unsigned_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_Y1_unsigned_int), xUserdef,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y1_unsigned_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE long_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",35,9)
******/
#ifndef XTNOUSE_long_int
tSDLTypeInfo ySDL_z_U2ctypes_Y2_long_int = {type_SDL_LongInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y2_long_int) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("long_int") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y2_long_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y2_long_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "long_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_Y2_long_int), xUserdef, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y2_long_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE unsigned_long_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",47,9)
******/
#ifndef XTNOUSE_unsigned_long_int
tSDLTypeInfo ySDL_z_U2ctypes_Y3_unsigned_long_int = {type_SDL_UnsignedLongInt,
  0, (xptrint)sizeof(z_U2ctypes_Y3_unsigned_long_int) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("unsigned_long_int")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y3_unsigned_long_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y3_unsigned_long_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "unsigned_long_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_Y3_unsigned_long_int), xUserdef,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y3_unsigned_long_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE long_long_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",59,9)
******/
#ifndef XTNOUSE_long_long_int
tSDLTypeInfo ySDL_z_U2ctypes_Y4_long_long_int = {type_SDL_LongLongInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y4_long_long_int) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("long_long_int")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y4_long_long_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y4_long_long_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "long_long_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_Y4_long_long_int), xUserdef,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y4_long_long_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE unsigned_long_long_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",73,9)
******/
#ifndef XTNOUSE_unsigned_long_long_int
tSDLTypeInfo ySDL_z_U2ctypes_Y5_unsigned_long_long_int =
  {type_SDL_UnsignedLongLongInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y5_unsigned_long_long_int) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("unsigned_long_long_int")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y5_unsigned_long_long_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y5_unsigned_long_long_int =
  {xSortEC , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "unsigned_long_long_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0)
  xEqF(0) xTestF(0), (xptrint)sizeof(z_U2ctypes_Y5_unsigned_long_long_int),
  xUserdef, (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y5_unsigned_long_long_int)
  XSRT_EXTRAS};
#endif

/*****
* SYNTYPE short_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",89,9)
******/
#ifndef XTNOUSE_short_int
tSDLTypeInfo ySDL_z_U2ctypes_Y6_short_int = {type_SDL_ShortInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y6_short_int) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("short_int") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y6_short_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y6_short_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "short_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_Y6_short_int), xUserdef, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y6_short_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE unsigned_short_int  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",102,9)
******/
#ifndef XTNOUSE_unsigned_short_int
tSDLTypeInfo ySDL_z_U2ctypes_Y7_unsigned_short_int =
  {type_SDL_UnsignedShortInt, 0,
  (xptrint)sizeof(z_U2ctypes_Y7_unsigned_short_int) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("unsigned_short_int")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y7_unsigned_short_int)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y7_unsigned_short_int = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "unsigned_short_int" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_Y7_unsigned_short_int), xUserdef,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y7_unsigned_short_int) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE char  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",114,9)
******/
#ifndef XTNOUSE_char
tSDLGenInfo ySDL_z_U2ctypes_Y8_char = {type_SDL_Syntype, 0,
  (xptrint)sizeof(z_U2ctypes_Y8_char) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("char") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y8_char), (tSDLTypeInfo *)&ySDL_SDL_Character};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y8_char = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes, "char" xIdNumber(0)
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_Y8_char), xSyntype, &xSrtR_SDL_Character,
  &xSrtR_SDL_Character, 0, 255, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y8_char) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE signed_char  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",121,9)
******/
#ifndef XTNOUSE_signed_char
tSDLGenInfo ySDL_z_U2ctypes_Y9_signed_char = {type_SDL_Syntype, 0,
  (xptrint)sizeof(z_U2ctypes_Y9_signed_char) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("signed_char") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_Y9_signed_char), (tSDLTypeInfo *)&ySDL_SDL_Character};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y9_signed_char = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "signed_char" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_Y9_signed_char), xSyntype,
  &xSrtR_SDL_Character, &xSrtR_SDL_Character, 0, 255, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_Y9_signed_char) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE unsigned_char  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",128,9)
******/
#ifndef XTNOUSE_unsigned_char
tSDLGenInfo ySDL_z_U2ctypes_YA_unsigned_char = {type_SDL_Syntype, 0,
  (xptrint)sizeof(z_U2ctypes_YA_unsigned_char) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("unsigned_char")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_YA_unsigned_char),
  (tSDLTypeInfo *)&ySDL_SDL_Character};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_YA_unsigned_char = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "unsigned_char" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(0), (xptrint)sizeof(z_U2ctypes_YA_unsigned_char), xSyntype,
  &xSrtR_SDL_Character, &xSrtR_SDL_Character, 0, 255, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_YA_unsigned_char) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE float  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",139,9)
******/
#ifndef XTNOUSE_float
tSDLTypeInfo ySDL_float = {type_SDL_Float, 0, (xptrint)sizeof(float)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("float")
  xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes) xRaWF(&ySrtR_float)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_float = {xSortEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yPacR_z_U2ctypes__U2ctypes, "float" xIdNumber(0) XCOMMON_EXTRAS
  xFreF(0) xAssF(0) xEqF(0) xTestF(0), (xptrint)sizeof(float), xUserdef,
  (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0 xRaWF((tSDLTypeInfo *)&ySDL_float)
  XSRT_EXTRAS};
#endif

/*****
* SYNTYPE double  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",148,9)
******/
#ifndef XTNOUSE_double
tSDLGenInfo ySDL_z_U2ctypes_YC_double = {type_SDL_Syntype, 0,
  (xptrint)sizeof(z_U2ctypes_YC_double) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("double") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_YC_double), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_YC_double = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes, "double" xIdNumber(0)
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_YC_double), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0 xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_YC_double)
  XSRT_EXTRAS};
#endif

/*****
* NEWTYPE ptr_void  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",155,9)
******/
#ifndef XTNOUSE_ptr_void
tSDLTypeInfo ySDL_z_U2ctypes_H0_ptr_void = {type_SDL_Voidstar, 0,
  (xptrint)sizeof(z_U2ctypes_H0_ptr_void) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("ptr_void") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_H0_ptr_void)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_H0_ptr_void = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "ptr_void" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_H0_ptr_void), xUserdef, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_H0_ptr_void) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE ptr_char  (BODY section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",172,9)
******/
#ifndef XTNOUSE_ptr_char
tSDLGenInfo ySDL_z_U2ctypes_H1_ptr_char = {type_SDL_Charstar, 0,
  (xptrint)sizeof(z_U2ctypes_H1_ptr_char) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("ptr_char") xRaWF((xIdNode)&yPacR_z_U2ctypes__U2ctypes)
  xRaWF(&ySrtR_z_U2ctypes_H1_ptr_char), &ySDL_SDL_Character};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_U2ctypes_H1_ptr_char = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_U2ctypes__U2ctypes,
  "ptr_char" xIdNumber(0) XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_U2ctypes_H1_ptr_char), xUserdef, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_U2ctypes_H1_ptr_char) XSRT_EXTRAS};
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",197,15) */
extern SDL_Charstring z_U2ctypes_H1O0_ToString(z_U2ctypes_H1_ptr_char C)
{
  SDL_Charstring Result;
  int i = 0;
  if (C != 0) {
    i = strlen(C);
  }
  Result = (SDL_Charstring)XALLOC(i+2, (tSDLTypeInfo *)&ySDL_SDL_Charstring);
  if (i>0) {
    memcpy(Result+1, C, i);
  }
  Result[0] = 'T';
  Result[i+1] = '\0';
  return Result;
}

extern z_U2ctypes_H1_ptr_char z_U2ctypes_H1O1_To_ptr_char(SDL_Charstring C)
{
  z_U2ctypes_H1_ptr_char Result;
  int i = 0;
  if (C != (SDL_Charstring)0) {
    i = strlen(C)-1;
  }
  Result = (z_U2ctypes_H1_ptr_char)XALLOC(i+1, (tSDLTypeInfo *)&ySDL_z_U2ctypes_H1_ptr_char);
  if (i>0) {
    memcpy(Result, C+1, i);
  }
  Result[i] = '\0';
  if ((C != 0) && (C[0] == 'T')) {
    xFree_SDL_Charstring((void **)&C);
  }
  return Result;
}

#if (!defined(XTIMEASINT_TICKS)) && (!defined(XTIMEASINT_SECS))
SDL_Duration z_U2ctypes_H1OB_Int2Dur (SDL_Integer I)
{
  SDL_Duration D;
  D.s = I;
  D.ns = 0;
  return D;
}

#ifndef XNOUSEOFREAL
SDL_Duration z_U2ctypes_H1OC_Real2Dur (SDL_Real R)
{
  SDL_Duration D;
  D.s = (xint32)R;
  D.ns = (xint32)((R-(SDL_Real)D.s)*1E9);
  return D;
}

SDL_Real z_U2ctypes_H1OD_Dur2Real (SDL_Duration D)
{
  return (SDL_Real)D.s + (SDL_Real)D.ns*(SDL_Real)1E-9;
}
#endif
#endif


/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_U2ctypes (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_U2ctypes__U2ctypes);
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_H0_ptr_void);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_H1_ptr_char);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y0_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y1_unsigned_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y2_long_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y3_unsigned_long_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y4_long_long_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y5_unsigned_long_long_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y6_short_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y7_unsigned_short_int);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y8_char);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_Y9_signed_char);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_YA_unsigned_char);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_float);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_U2ctypes_YC_double);
#endif
}
