
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#ifndef XX_U2ctypes_H
#define XX_U2ctypes_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE U2ctypes
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\u2ctypes.sdl",15,9)
******/
extern XCONST struct xPackageIdStruct yPacR_z_U2ctypes__U2ctypes;

extern void yInit_U2ctypes (void);

/*****
* GENERATOR CArray  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",299,11)
******/

/*****
* GENERATOR Ref  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\CPointer.pr",13,11)
******/

/*****
* SYNTYPE int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",13,9)
******/
#ifndef XTNOUSE_int
extern tSDLGenInfo ySDL_z_U2ctypes_Y0_int;
#endif
typedef SDL_Integer  z_U2ctypes_Y0_int;

/*****
* SYNTYPE unsigned_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",21,9)
******/
#ifndef XTNOUSE_unsigned_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y1_unsigned_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",21,24) */
typedef unsigned int z_U2ctypes_Y1_unsigned_int;


/*****
* SYNTYPE long_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",35,9)
******/
#ifndef XTNOUSE_long_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y2_long_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",35,20) */
typedef long int z_U2ctypes_Y2_long_int;


/*****
* SYNTYPE unsigned_long_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",47,9)
******/
#ifndef XTNOUSE_unsigned_long_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y3_unsigned_long_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",47,29) */
typedef unsigned long int z_U2ctypes_Y3_unsigned_long_int;


/*****
* SYNTYPE long_long_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",59,9)
******/
#ifndef XTNOUSE_long_long_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y4_long_long_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",59,25) */
#ifndef XNOUSE_LONG_LONG
typedef xlonglong z_U2ctypes_Y4_long_long_int;
#endif


/*****
* SYNTYPE unsigned_long_long_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",73,9)
******/
#ifndef XTNOUSE_unsigned_long_long_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y5_unsigned_long_long_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",73,34) */
#ifndef XNOUSE_LONG_LONG
typedef unsigned xlonglong z_U2ctypes_Y5_unsigned_long_long_int;
#endif


/*****
* SYNTYPE short_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",89,9)
******/
#ifndef XTNOUSE_short_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y6_short_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",89,21) */
typedef short int z_U2ctypes_Y6_short_int;


/*****
* SYNTYPE unsigned_short_int  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",102,9)
******/
#ifndef XTNOUSE_unsigned_short_int
extern tSDLTypeInfo ySDL_z_U2ctypes_Y7_unsigned_short_int;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",102,30) */
typedef unsigned short int z_U2ctypes_Y7_unsigned_short_int;


/*****
* SYNTYPE char  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",114,9)
******/
#ifndef XTNOUSE_char
extern tSDLGenInfo ySDL_z_U2ctypes_Y8_char;
#endif
typedef SDL_Character  z_U2ctypes_Y8_char;

/*****
* SYNTYPE signed_char  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",121,9)
******/
#ifndef XTNOUSE_signed_char
extern tSDLGenInfo ySDL_z_U2ctypes_Y9_signed_char;
#endif
typedef SDL_Character  z_U2ctypes_Y9_signed_char;

/*****
* SYNTYPE unsigned_char  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",128,9)
******/
#ifndef XTNOUSE_unsigned_char
extern tSDLGenInfo ySDL_z_U2ctypes_YA_unsigned_char;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",128,25) */
typedef unsigned char z_U2ctypes_YA_unsigned_char;


/*****
* SYNTYPE float  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",139,9)
******/
#ifndef XTNOUSE_float
extern tSDLTypeInfo ySDL_float;
#endif

/*****
* SYNTYPE double  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",148,9)
******/
#ifndef XTNOUSE_double
extern tSDLGenInfo ySDL_z_U2ctypes_YC_double;
#endif
typedef SDL_Real  z_U2ctypes_YC_double;

/*****
* NEWTYPE ptr_void  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",155,9)
******/
#ifndef XTNOUSE_ptr_void
extern tSDLTypeInfo ySDL_z_U2ctypes_H0_ptr_void;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",158,15) */
typedef void * z_U2ctypes_H0_ptr_void;


/*****
* NEWTYPE ptr_char  (TYPE section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",172,9)
******/
#ifndef XTNOUSE_ptr_char
extern tSDLGenInfo ySDL_z_U2ctypes_H1_ptr_char;
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",197,15) */
typedef char * z_U2ctypes_H1_ptr_char;



/*****
* GENERATOR CArray  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",299,11)
******/

/*****
* GENERATOR Ref  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\CPointer.pr",13,11)
******/

/*****
* SYNTYPE int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",13,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y0_int;
#define ySrtN_z_U2ctypes_Y0_int  (&ySrtR_z_U2ctypes_Y0_int)
#endif

#define yAssF_z_U2ctypes_Y0_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y0_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y0_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y0_int
#define ANY_z_U2ctypes_Y0_int ANY_SDL_Integer
#endif

/*****
* SYNTYPE unsigned_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",21,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y1_unsigned_int;
#define ySrtN_z_U2ctypes_Y1_unsigned_int  (&ySrtR_z_U2ctypes_Y1_unsigned_int)
#endif

#define yAssF_z_U2ctypes_Y1_unsigned_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y1_unsigned_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y1_unsigned_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y1_unsigned_int
#define ANY_z_U2ctypes_Y1_unsigned_int
#endif

/*****
* SYNTYPE long_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",35,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y2_long_int;
#define ySrtN_z_U2ctypes_Y2_long_int  (&ySrtR_z_U2ctypes_Y2_long_int)
#endif

#define yAssF_z_U2ctypes_Y2_long_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y2_long_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y2_long_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y2_long_int
#define ANY_z_U2ctypes_Y2_long_int
#endif

/*****
* SYNTYPE unsigned_long_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",47,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y3_unsigned_long_int;
#define ySrtN_z_U2ctypes_Y3_unsigned_long_int  (&ySrtR_z_U2ctypes_Y3_unsigned_long_int)
#endif

#define yAssF_z_U2ctypes_Y3_unsigned_long_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y3_unsigned_long_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y3_unsigned_long_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y3_unsigned_long_int
#define ANY_z_U2ctypes_Y3_unsigned_long_int
#endif

/*****
* SYNTYPE long_long_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",59,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y4_long_long_int;
#define ySrtN_z_U2ctypes_Y4_long_long_int  (&ySrtR_z_U2ctypes_Y4_long_long_int)
#endif

#define yAssF_z_U2ctypes_Y4_long_long_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y4_long_long_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y4_long_long_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y4_long_long_int
#define ANY_z_U2ctypes_Y4_long_long_int
#endif

/*****
* SYNTYPE unsigned_long_long_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",73,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y5_unsigned_long_long_int;
#define ySrtN_z_U2ctypes_Y5_unsigned_long_long_int  (&ySrtR_z_U2ctypes_Y5_unsigned_long_long_int)
#endif

#define yAssF_z_U2ctypes_Y5_unsigned_long_long_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y5_unsigned_long_long_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y5_unsigned_long_long_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y5_unsigned_long_long_int
#define ANY_z_U2ctypes_Y5_unsigned_long_long_int
#endif

/*****
* SYNTYPE short_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",89,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y6_short_int;
#define ySrtN_z_U2ctypes_Y6_short_int  (&ySrtR_z_U2ctypes_Y6_short_int)
#endif

#define yAssF_z_U2ctypes_Y6_short_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y6_short_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y6_short_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y6_short_int
#define ANY_z_U2ctypes_Y6_short_int
#endif

/*****
* SYNTYPE unsigned_short_int  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",102,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y7_unsigned_short_int;
#define ySrtN_z_U2ctypes_Y7_unsigned_short_int  (&ySrtR_z_U2ctypes_Y7_unsigned_short_int)
#endif

#define yAssF_z_U2ctypes_Y7_unsigned_short_int(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_U2ctypes_Y7_unsigned_short_int(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y7_unsigned_short_int(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y7_unsigned_short_int
#define ANY_z_U2ctypes_Y7_unsigned_short_int
#endif

/*****
* SYNTYPE char  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",114,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y8_char;
#define ySrtN_z_U2ctypes_Y8_char  (&ySrtR_z_U2ctypes_Y8_char)
#endif

#define yAssF_z_U2ctypes_Y8_char(V,E,A)  yAssF_SDL_Character(V,E,A)
#define yEqF_z_U2ctypes_Y8_char(Expr1,Expr2)  yEqF_SDL_Character(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y8_char(Expr1,Expr2)  yNEqF_SDL_Character(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y8_char
#define ANY_z_U2ctypes_Y8_char ANY_SDL_Character
#endif

/*****
* SYNTYPE signed_char  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",121,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_Y9_signed_char;
#define ySrtN_z_U2ctypes_Y9_signed_char  (&ySrtR_z_U2ctypes_Y9_signed_char)
#endif

#define yAssF_z_U2ctypes_Y9_signed_char(V,E,A)  yAssF_SDL_Character(V,E,A)
#define yEqF_z_U2ctypes_Y9_signed_char(Expr1,Expr2)  yEqF_SDL_Character(Expr1,Expr2)
#define yNEqF_z_U2ctypes_Y9_signed_char(Expr1,Expr2)  yNEqF_SDL_Character(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_Y9_signed_char
#define ANY_z_U2ctypes_Y9_signed_char ANY_SDL_Character
#endif

/*****
* SYNTYPE unsigned_char  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",128,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_YA_unsigned_char;
#define ySrtN_z_U2ctypes_YA_unsigned_char  (&ySrtR_z_U2ctypes_YA_unsigned_char)
#endif

#define yAssF_z_U2ctypes_YA_unsigned_char(V,E,A)  yAssF_SDL_Character(V,E,A)
#define yEqF_z_U2ctypes_YA_unsigned_char(Expr1,Expr2)  yEqF_SDL_Character(Expr1,Expr2)
#define yNEqF_z_U2ctypes_YA_unsigned_char(Expr1,Expr2)  yNEqF_SDL_Character(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_YA_unsigned_char
#define ANY_z_U2ctypes_YA_unsigned_char
#endif

/*****
* SYNTYPE float  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",139,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_float;
#define ySrtN_float  (&ySrtR_float)
#endif

#define yAssF_float(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_float(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_float(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#ifndef ANY_float
#define ANY_float
#endif

/*****
* SYNTYPE double  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",148,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_YC_double;
#define ySrtN_z_U2ctypes_YC_double  (&ySrtR_z_U2ctypes_YC_double)
#endif

#define yAssF_z_U2ctypes_YC_double(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_U2ctypes_YC_double(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_U2ctypes_YC_double(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#ifndef ANY_z_U2ctypes_YC_double
#define ANY_z_U2ctypes_YC_double ANY_SDL_Real
#endif

/*****
* NEWTYPE ptr_void  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",155,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_H0_ptr_void;
#define ySrtN_z_U2ctypes_H0_ptr_void  (&ySrtR_z_U2ctypes_H0_ptr_void)
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",158,15) */
#define z_U2ctypes_H0F0_Null()       0


#define yAssF_z_U2ctypes_H0_ptr_void(V,E,A)  V = E
#define yEqF_z_U2ctypes_H0_ptr_void(Expr1,Expr2)  ((Expr1) == (Expr2))
#define yNEqF_z_U2ctypes_H0_ptr_void(Expr1,Expr2)  ((Expr1) != (Expr2))
#ifndef ANY_z_U2ctypes_H0_ptr_void
#define ANY_z_U2ctypes_H0_ptr_void
#endif
#define z_U2ctypes_H0O3_copy(P)  (P)

/*****
* NEWTYPE ptr_char  (HEADING section)
* <<PACKAGE U2ctypes>>
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",172,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_U2ctypes_H1_ptr_char;
#define ySrtN_z_U2ctypes_H1_ptr_char  (&ySrtR_z_U2ctypes_H1_ptr_char)
#endif
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\BasicCTypes.pr",197,15) */
#define z_U2ctypes_H1F0_Null()       0
extern SDL_Charstring z_U2ctypes_H1O0_ToString (z_U2ctypes_H1_ptr_char C);
extern z_U2ctypes_H1_ptr_char z_U2ctypes_H1O1_To_ptr_char (SDL_Charstring C);
#define xPlus_ptr_char(P1,P2)  ((P1)+(P2))
#define xMinus_ptr_char(P1,P2)  ((P1)-(P2))
#define z_U2ctypes_H1O8_free(P) XFREE((void**)P,0)
#define z_U2ctypes_H1O7_alloc(P) (z_U2ctypes_H1_ptr_char)XALLOC(P,0)
#define z_U2ctypes_H1OH_num(P)   ((SDL_Integer)P)

#if (!defined(XTIMEASINT_TICKS)) && (!defined(XTIMEASINT_SECS))
  extern SDL_Duration z_U2ctypes_H1OB_Int2Dur (SDL_Integer I);
  #ifndef XNOUSEOFREAL
    extern SDL_Duration z_U2ctypes_H1OC_Real2Dur (SDL_Real R);
    extern SDL_Real z_U2ctypes_H1OD_Dur2Real (SDL_Duration D);
  #endif
#elif (defined(XTIMEASINT_SECS))
  #define z_U2ctypes_H1OB_Int2Dur(I)  (SDL_Duration)((I)*SDT_TICKPERSEC)
  #define z_U2ctypes_H1OC_Real2Dur(R) (SDL_Duration)((R)*SDT_TICKPERSEC)
  #define z_U2ctypes_H1OD_Dur2Real(D) (((SDL_Real)(D))/SDT_TICKPERSEC)
#else
  #define z_U2ctypes_H1OB_Int2Dur(I)  (SDL_Duration)(I)
  #define z_U2ctypes_H1OC_Real2Dur(R) (SDL_Duration)(R)
  #define z_U2ctypes_H1OD_Dur2Real(D) (SDL_Real)(D)
#endif
#define z_U2ctypes_H1OE_Int2Time(I)   z_U2ctypes_H1OB_Int2Dur(I)
#define z_U2ctypes_H1OF_Real2Time(R)  z_U2ctypes_H1OC_Real2Dur(R)
#define z_U2ctypes_H1OG_Time2Real(D)  z_U2ctypes_H1OD_Dur2Real(D)



#define yAssF_z_U2ctypes_H1_ptr_char(V,E,A)  V = E
#define yEqF_z_U2ctypes_H1_ptr_char(Expr1,Expr2)  ((Expr1) == (Expr2))
#define yNEqF_z_U2ctypes_H1_ptr_char(Expr1,Expr2)  ((Expr1) != (Expr2))
#ifndef ANY_z_U2ctypes_H1_ptr_char
#define ANY_z_U2ctypes_H1_ptr_char
#endif
#define z_U2ctypes_H1OL_copy(P)  (P)

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
