
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#ifndef XX_App_H
#define XX_App_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE App
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#GH3ptI02T75L8NkfuLfWX0KE|pos(1,9)")
******/
extern XCONST struct xPackageIdStruct yPacR_z_App__App;

extern void yInit_App (void);

/*****
* BLOCK TYPE Class2
* <<PACKAGE App>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#7rdrCLGQK1CLhXJZSLqRIG-V|pos(1,16)")
******/
extern XCONST struct xBlockIdStruct yBloR_z_App_Z0_Class2;
#define yPrsE_z_App_Z0P0_OS  0
#define yPrsE_z_App_Z0P1_part__implicit_process_0  1
#define yChaE_z_App_Z0G0_implicit_port_2  2

/*****
* PROCESS TYPE @implicit_process_0
* <<PACKAGE App/BLOCK TYPE Class2>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,22)")
******/
extern XCONST XSIGTYPE yPrsS_z_App_Z0T0_implicit_process_0[];
extern XCONST xStateIdNode yPrsT_z_App_Z0T0_implicit_process_0[];
extern XCONST struct xPrsIdStruct yPrsR_z_App_Z0T0_implicit_process_0;
#define yPrsN_z_App_Z0T0_implicit_process_0  (&yPrsR_z_App_Z0T0_implicit_process_0)
#ifdef XCOVERAGE
extern long int yPrsC_z_App_Z0T0_implicit_process_0[];
#endif
YPAD_PROTOTYPE(yPAD_z_App_Z0T0_implicit_process_0)
extern XCONST struct xSignalIdStruct ySigR_z_App_Z0T0_implicit_process_0;
#define ySigN_z_App_Z0T0_implicit_process_0  (&ySigR_z_App_Z0T0_implicit_process_0)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} ySignalPar_z_App_Z0T0_implicit_process_0;
typedef ySignalPar_z_App_Z0T0_implicit_process_0  *yPDP_z_App_Z0T0_implicit_process_0;
XPROCESSDEF_H(implicit_process_0, \
  "implicit_process_0",z_App_Z0T0_implicit_process_0, \
  yPAD_z_App_Z0T0_implicit_process_0,yVDef_z_App_Z0T0_implicit_process_0)
#define yChaE_z_App_Z0T0G0_implicit_port_1  0
#ifdef XBREAKBEFORE
#define ySym_z_App_Z0T0_implicit_process_0  3
extern char * yRef_z_App_Z0T0_implicit_process_0 (int, xSymbolType *);
#endif
typedef struct {
  PROCESS_VARS
} yVDef_z_App_Z0T0_implicit_process_0;
typedef yVDef_z_App_Z0T0_implicit_process_0  *yVDP_z_App_Z0T0_implicit_process_0;
extern void yFree_z_App_Z0T0_implicit_process_0 (void *);
extern void yIni_z_App_Z0T0_implicit_process_0 (xPrsNode);

/*****
* PROCEDURE find
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#tfkItV0j--DLGKhjqL4EHZrV|pos(1,23)")
******/
YPRD_PROTOTYPE(z_App_Z0T0O0_find)
extern XCONST struct xPrdIdStruct yPrdR_z_App_Z0T0O0_find;
#define yPrdN_z_App_Z0T0O0_find  (&yPrdR_z_App_Z0T0O0_find)
#ifdef XBREAKBEFORE
#define ySym_z_App_Z0T0O0_find  4
extern char * yRef_z_App_Z0T0O0_find (int, xSymbolType *);
#endif
typedef struct {
  PROCEDURE_VARS
} yVDef_z_App_Z0T0O0_find;
typedef yVDef_z_App_Z0T0O0_find  *yVDP_z_App_Z0T0O0_find;
extern void yFree_z_App_Z0T0O0_find (void *);

/*****
* STATE waiting
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0
*     /PROCEDURE find>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#UnImyLbmEg5LNqUhDLRgO*OV|pos(1,23)")
******/
#define z_App_Z0T0O0E0_waiting  1
extern XCONST struct xStateIdStruct yStaR_z_App_Z0T0O0E0_waiting;
#define yStaN_z_App_Z0T0O0E0_waiting  (&yStaR_z_App_Z0T0O0E0_waiting)

/*****
* STATE waitOsek
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#VsoDDLb4nPSLw*B9bIluPZKE|pos(1,19)")
******/
#define z_App_Z0T0E0_waitOsek  1
extern XCONST struct xStateIdStruct yStaR_z_App_Z0T0E0_waitOsek;
#define yStaN_z_App_Z0T0E0_waitOsek  (&yStaR_z_App_Z0T0E0_waitOsek)

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
