
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#ifndef XX_App_H
#define XX_App_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE App
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#GH3ptI02T75L8NkfuLfWX0KE|pos(1,9)")
******/
extern XCONST struct xPackageIdStruct yPacR_z_App__App;

extern void yInit_App (void);

/*****
* PROCESS TYPE Class2
* <<PACKAGE App>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#7rdrCLGQK1CLhXJZSLqRIG-V|pos(1,18)")
******/
extern XCONST XSIGTYPE yPrsS_z_App_T0_Class2[];
extern XCONST xStateIdNode yPrsT_z_App_T0_Class2[];
extern XCONST struct xPrsIdStruct yPrsR_z_App_T0_Class2;
#define yPrsN_z_App_T0_Class2  (&yPrsR_z_App_T0_Class2)
#ifdef XCOVERAGE
extern long int yPrsC_z_App_T0_Class2[];
#endif
YPAD_PROTOTYPE(yPAD_z_App_T0_Class2)
extern XCONST struct xSignalIdStruct ySigR_z_App_T0_Class2;
#define ySigN_z_App_T0_Class2  (&ySigR_z_App_T0_Class2)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} ySignalPar_z_App_T0_Class2;
typedef ySignalPar_z_App_T0_Class2  *yPDP_z_App_T0_Class2;
XPROCESSDEF_H(Class2,"Class2",z_App_T0_Class2,yPAD_z_App_T0_Class2, \
  yVDef_z_App_T0_Class2)
#define yChaE_z_App_T0G0_implicit_port_1  0
#ifdef XBREAKBEFORE
#define ySym_z_App_T0_Class2  3
extern char * yRef_z_App_T0_Class2 (int, xSymbolType *);
#endif
typedef struct {
  PROCESS_VARS
                /* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#oSkOcEDwmGELMKBYMVxF0U1L|pos(1,13)") */
  SDL_PId z_App_T0F0_OS;
} yVDef_z_App_T0_Class2;
typedef yVDef_z_App_T0_Class2  *yVDP_z_App_T0_Class2;
extern void yFree_z_App_T0_Class2 (void *);
extern void yIni_z_App_T0_Class2 (xPrsNode);

/*****
* PROCEDURE find
* <<PACKAGE App/PROCESS TYPE Class2>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#tfkItV0j--DLGKhjqL4EHZrV|pos(1,19)")
******/
YPRD_PROTOTYPE(z_App_T0O0_find)
extern XCONST struct xPrdIdStruct yPrdR_z_App_T0O0_find;
#define yPrdN_z_App_T0O0_find  (&yPrdR_z_App_T0O0_find)
#ifdef XBREAKBEFORE
#define ySym_z_App_T0O0_find  4
extern char * yRef_z_App_T0O0_find (int, xSymbolType *);
#endif
typedef struct {
  PROCEDURE_VARS
} yVDef_z_App_T0O0_find;
typedef yVDef_z_App_T0O0_find  *yVDP_z_App_T0O0_find;
extern void yFree_z_App_T0O0_find (void *);

/*****
* STATE waiting
* <<PACKAGE App/PROCESS TYPE Class2/PROCEDURE find>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#UnImyLbmEg5LNqUhDLRgO*OV|pos(1,19)")
******/
#define z_App_T0O0E0_waiting  1
extern XCONST struct xStateIdStruct yStaR_z_App_T0O0E0_waiting;
#define yStaN_z_App_T0O0E0_waiting  (&yStaR_z_App_T0O0E0_waiting)

/*****
* STATE waitOsek
* <<PACKAGE App/PROCESS TYPE Class2>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#VsoDDLb4nPSLw*B9bIluPZKE|pos(1,15)")
******/
#define z_App_T0E0_waitOsek  1
extern XCONST struct xStateIdStruct yStaR_z_App_T0E0_waitOsek;
#define yStaN_z_App_T0E0_waitOsek  (&yStaR_z_App_T0E0_waitOsek)

/*****
* DCL OS
* <<PACKAGE App/PROCESS TYPE Class2>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#oSkOcEDwmGELMKBYMVxF0U1L|pos(1,13)")
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z_App_T0F0_OS;
#endif

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
