
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ExtraOps.h"
#include "U2ctypes.h"
#include "osek.h"
#include "App.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "Class2.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "App.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE App
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#GH3ptI02T75L8NkfuLfWX0KE|pos(1,9)")
******/
XCONST struct xPackageIdStruct yPacR_z_App__App = {xPackageEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "App" xIdNumber(0) XCOMMON_EXTRAS
  xIdNames(0) XPAC_EXTRAS};

/*****
* BLOCK TYPE Class2
* <<PACKAGE App>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#7rdrCLGQK1CLhXJZSLqRIG-V|pos(1,16)")
******/
XCONST struct xBlockIdStruct yBloR_z_App_Z0_Class2 = {xBlockTypeEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_App__App, "Class2" xIdNumber(0)
  XCOMMON_EXTRAS, (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0,
  (xViewListRec *)0, (xViewIndexRec *)0 xNrInst(1), 1, 0, (xPrsIdNode)0
  xTrace(-1) xMSCETrace(-1) xGRTrace(-1) xMSCETrace(0) XBLO_EXTRAS};

/*****
* PROCESS TYPE @implicit_process_0
* <<PACKAGE App/BLOCK TYPE Class2>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,22)")
******/
#ifdef XCOVERAGE
long int yPrsC_z_App_Z0T0_implicit_process_0[ySym_z_App_Z0T0_implicit_process_0+1];
#endif
XCONST XSIGTYPE yPrsS_z_App_Z0T0_implicit_process_0[] =
  {SIGNAL_NAME(pREPLY_response, &ySigR_pREPLY_z_osek_I0_response), (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z_App_Z0T0_implicit_process_0[] = {&xStartStateIdRec,
  &yStaR_z_App_Z0T0E0_waitOsek};
static xIdNode yPrsO_z_App_Z0T0_implicit_process_0[] = {(xIdNode)0, (xIdNode)0};
static XPRSNODE yPrsA_z_App_Z0T0_implicit_process_0 = (XPRSNODE)0;
static XPRSNODE yPrsB_z_App_Z0T0_implicit_process_0 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z_App_Z0T0_implicit_process_0 =
  {xProcessTypeEC , (xIdNode)0, (xIdNode)0, (xIdNode)&yBloR_z_App_Z0_Class2,
  "@implicit_process_0" xIdNumber(0) XCOMMON_EXTRAS,
  yPrsT_z_App_Z0T0_implicit_process_0, yPrsS_z_App_Z0T0_implicit_process_0
  xOptChan(yPrsO_z_App_Z0T0_implicit_process_0),
  &ySigR_z_App_Z0T0_implicit_process_0, -1 xNrInst(1), 0,
  &yPrsB_z_App_Z0T0_implicit_process_0,
  (xptrint)sizeof(yVDef_z_App_Z0T0_implicit_process_0)
  xPrsPrioPar(xDefaultPrioProcess), &yPrsA_z_App_Z0T0_implicit_process_0
  xTrace(-1) xGRTrace(-1) xBreakB(yRef_z_App_Z0T0_implicit_process_0)
  xBreakB(ySym_z_App_Z0T0_implicit_process_0) xBreakB(0) xMSCETrace(-1)
  xCoverage(yPrsC_z_App_Z0T0_implicit_process_0) xCoverage(0) xCoverage(0),
  yPAD_z_App_Z0T0_implicit_process_0, yFree_z_App_Z0T0_implicit_process_0,
  yIni_z_App_Z0T0_implicit_process_0, (xPrsIdNode)0, (xPrdIdNode *)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,22)\")")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z_App_Z0T0_implicit_process_0)};
static xSignalNode ySigA_z_App_Z0T0_implicit_process_0 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_App_Z0T0_implicit_process_0 =
  {xStartUpSignalEC , (xIdNode)0, (xIdNode)0, (xIdNode)&yBloR_z_App_Z0_Class2
  xIdNames("-") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_App_Z0T0_implicit_process_0),
  &ySigA_z_App_Z0T0_implicit_process_0, 0 xFreS(0) SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,22)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XPROCESSDEF_C(implicit_process_0,
  "implicit_process_0",z_App_Z0T0_implicit_process_0,
  yPAD_z_App_Z0T0_implicit_process_0,yVDef_z_App_Z0T0_implicit_process_0)
void yFree_z_App_Z0T0_implicit_process_0(void *yVarP)
{
}
void yIni_z_App_Z0T0_implicit_process_0(xPrsNode VarP)
{
  yVDef_z_App_Z0T0_implicit_process_0 *yVarP = (yVDef_z_App_Z0T0_implicit_process_0 *)VarP;
}

/*+++++
* GR ref function for process @implicit_process_0
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,41)")
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z_App_Z0T0_implicit_process_0 (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#KHYKmLVWiBiLDpZddVNqOIgV|pos(1,13)\")";
    case 2: *SymbolType = xsProcedureCall;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#lMFuTISUqJlLPY4YyER8GDxE|pos(1,25)\")";
    case 3: *SymbolType = xsNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#yhoNgEnmjKLLwIvhHVzXp5QE|pos(1,17)\")";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process @implicit_process_0
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#o6WzcVa*xnSLitcbZI*eAPWV|pos(1,41)")
++++++*/
YPAD_FUNCTION(yPAD_z_App_Z0T0_implicit_process_0)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z_App_Z0T0_implicit_process_0)
  YPAD_TEMP_VARS
  YPRSNAME_VAR("@implicit_process_0")

  BEGIN_PAD(yVDef_z_App_Z0T0_implicit_process_0)
#ifndef XNOPROCATSTARTUP
  {
    xPrdNode ActivePrd;
    ActivePrd = xGetActivePrd((xPrsNode)yVarP);
    while (ActivePrd != 0) {
#ifdef XVALIDATOR_LIB
      if ((*ActivePrd->RestartPRD)(VarP, ndstate)) {
#else
      if ((*ActivePrd->RestartPRD)(VarP)) {
#endif
        return;
      }
      ActivePrd = xGetActivePrd((xPrsNode)yVarP);
#ifdef XBREAKBEFORE
      if (ActivePrd != 0) {
        XBETWEEN_SYMBOLS(ActivePrd->RestartAddress, 144)
      } else {
        XBETWEEN_SYMBOLS(yVarP->RestartAddress,  146)
      }
#endif
    }
  }
#endif

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#KHYKmLVWiBiLDpZddVNqOIgV|pos(1,13)") */
  case 0:
    BEGIN_START_TRANSITION(ySignalPar_z_App_Z0T0_implicit_process_0)
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS(2, 161)
    XBETWEEN_STMTS(2, 162)

/* ----- CALL find ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#lMFuTISUqJlLPY4YyER8GDxE|pos(1,25)") */
#ifdef XCASELABELS
  case 2:
#endif
    ALLOC_PROCEDURE(z_App_Z0T0O0_find, yPrdN_z_App_Z0T0O0_find,
      sizeof(yVDef_z_App_Z0T0O0_find))
    PROCEDURE_ALLOC_ERROR
    CALL_PROCEDURE(z_App_Z0T0O0_find, yPrdN_z_App_Z0T0O0_find, 0, 1)
    PROCEDURE_ALLOC_ERROR_END
#ifdef XCASEAFTERPRDLABELS
  case 1:
    ;
#endif
    XBETWEEN_SYMBOLS(3, 178)

/* ----- NEXTSTATE waitOsek ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#yhoNgEnmjKLLwIvhHVzXp5QE|pos(1,17)") */
#ifdef XCASELABELS
  case 3:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(waitOsek, z_App_Z0T0E0_waitOsek, "waitOsek")
  default : return;
  }
}

/*****
* STATE waitOsek
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#VsoDDLb4nPSLw*B9bIluPZKE|pos(1,19)")
******/
static XCONST xInputAction yStaH_z_App_Z0T0E0_waitOsek[] = {xDiscard};
static XCONST XINPUTREFTYPE yStaI_z_App_Z0T0E0_waitOsek[] = {0};
#ifdef XCOVERAGE
static long int yStaC_z_App_Z0T0E0_waitOsek[0+1];
#endif
XCONST struct xStateIdStruct yStaR_z_App_Z0T0E0_waitOsek = {xStateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z_App_Z0T0_implicit_process_0,
  "waitOsek" xIdNumber(0) XCOMMON_EXTRAS, z_App_Z0T0E0_waitOsek,
  yStaH_z_App_Z0T0E0_waitOsek, yStaI_z_App_Z0T0E0_waitOsek, 0, 0, 0
  xCoverage(yStaC_z_App_Z0T0E0_waitOsek), (xStateIdNode)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#VsoDDLb4nPSLw*B9bIluPZKE|pos(1,19)\")")
  XSTA_EXTRAS};

/*****
* PROCEDURE find
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#tfkItV0j--DLGKhjqL4EHZrV|pos(1,23)")
******/
#ifdef XCOVERAGE
long int yPrdC_z_App_Z0T0O0_find[ySym_z_App_Z0T0O0_find+1];
#endif
static XCONST xStateIdNode yPrdT_z_App_Z0T0O0_find[] = {&xStartStateIdRec,
  &yStaR_z_App_Z0T0O0E0_waiting};
static xPrdNode yPrdA_z_App_Z0T0O0_find = (xPrdNode)0;
XCONST struct xPrdIdStruct yPrdR_z_App_Z0T0O0_find = {xProcedureEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z_App_Z0T0_implicit_process_0,
  "find" xIdNumber(0) XCOMMON_EXTRAS, yPrdT_z_App_Z0T0O0_find,
  yPrsS_z_App_Z0T0_implicit_process_0, z_App_Z0T0O0_find,
  yFree_z_App_Z0T0O0_find, (xptrint)sizeof(yVDef_z_App_Z0T0O0_find),
  &yPrdA_z_App_Z0T0O0_find xBreakB(yRef_z_App_Z0T0O0_find)
  xBreakB(ySym_z_App_Z0T0O0_find) xBreakB(0)
  xCoverage(yPrdC_z_App_Z0T0O0_find), (xPrdIdNode)0, (xPrdIdNode *)0
  XPRD_EXTRAS};
void yFree_z_App_Z0T0O0_find(void *yVarP)
{
}

/*+++++
* GR ref function for procedure find
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#tfkItV0j--DLGKhjqL4EHZrV|pos(1,27)")
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z_App_Z0T0O0_find (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#4eU8ZEIKYoVLrthgyVFgywpI|pos(1,17)\")";
    case 1: *SymbolType = xspREPLYInput;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#1IqABIux8s0L0t7XVVkzEG-E|pos(1,29)\")";
    case 3: *SymbolType = xsRPC;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#1IqABIux8s0L0t7XVVkzEG-E|pos(1,29)\")";
    case 4: *SymbolType = xsNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#Dse2BV7VoXDLHhuj1Lo4A2gE|pos(1,21)\")";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for procedure find
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#tfkItV0j--DLGKhjqL4EHZrV|pos(1,27)")
++++++*/
YPRD_FUNCTION(z_App_Z0T0O0_find)
{
  YPAD_YSVARP
  YPRD_YVARP(yVDef_z_App_Z0T0_implicit_process_0)
  yVDef_z_App_Z0T0O0_find * yPrdVarP;
  YPRD_TEMP_VARS
  YPRDNAME_VAR("find")
    yPrdVarP = (yVDef_z_App_Z0T0O0_find *)xGetActivePrd((xPrsNode)yVarP);

  LOOP_LABEL_PRD
  switch (yPrdVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#4eU8ZEIKYoVLrthgyVFgywpI|pos(1,17)") */
  case 0:
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS_PRD(3, 274)
    XBETWEEN_STMTS_PRD(3, 275)

/* ----- REMOTE PROCEDURE CALL response ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#1IqABIux8s0L0t7XVVkzEG-E|pos(1,29)") */
#ifdef XCASELABELS
  case 3:
#endif
    ALLOC_SIGNAL(pCALL_response, ySigN_pCALL_z_osek_I0_response, TO_PROCESS(OS,
      xPrsInst((xIdNode)yVarP->InstNameNode,(xIdNode)&yBloR_z_App_Z0_Class2,
      yPrsE_z_App_Z0P0_OS)), XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    SDL_2OUTPUT_RPC_CALL(xDefaultPrioSignal, (xIdNode *)0, pCALL_response,
      ySigN_pCALL_z_osek_I0_response, TO_PROCESS(OS,
      xPrsInst((xIdNode)yVarP->InstNameNode,(xIdNode)&yBloR_z_App_Z0_Class2,
      yPrsE_z_App_Z0P0_OS)), 0, "pCALL_response")
    SIGNAL_ALLOC_ERROR_END
    XAT_LAST_SYMBOL
    SDL_RPCWAIT_NEXTSTATE_PRD(ySigN_pREPLY_z_osek_I0_response, pREPLY_response,
      1)

/*-----
* RPC Reply INPUT pREPLY_response
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#1IqABIux8s0L0t7XVVkzEG-E|pos(1,29)")
------*/
  case 1: ;
    XRPC_REPLY_INPUT_PRD
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("pREPLY_response")
    XBETWEEN_SYMBOLS_PRD(4, 303)

/* ----- NEXTSTATE waiting ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#Dse2BV7VoXDLHhuj1Lo4A2gE|pos(1,21)") */
#ifdef XCASELABELS
  case 4:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE_PRD(waiting, z_App_Z0T0O0E0_waiting, "waiting")
  }
  XEND_PRD
}

/*****
* STATE waiting
* <<PACKAGE App/BLOCK TYPE Class2/PROCESS TYPE @implicit_process_0
*     /PROCEDURE find>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#UnImyLbmEg5LNqUhDLRgO*OV|pos(1,23)")
******/
static XCONST xInputAction yStaH_z_App_Z0T0O0E0_waiting[] = {xDiscard};
static XCONST XINPUTREFTYPE yStaI_z_App_Z0T0O0E0_waiting[] = {0};
#ifdef XCOVERAGE
static long int yStaC_z_App_Z0T0O0E0_waiting[0+1];
#endif
XCONST struct xStateIdStruct yStaR_z_App_Z0T0O0E0_waiting = {xStateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrdR_z_App_Z0T0O0_find,
  "waiting" xIdNumber(0) XCOMMON_EXTRAS, z_App_Z0T0O0E0_waiting,
  yStaH_z_App_Z0T0O0E0_waiting, yStaI_z_App_Z0T0O0E0_waiting, 0, 0, 0
  xCoverage(yStaC_z_App_Z0T0O0E0_waiting), (xStateIdNode)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#UnImyLbmEg5LNqUhDLRgO*OV|pos(1,23)\")")
  XSTA_EXTRAS};

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_App (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_App__App);
  yInit_U2ExtraOps();
  yInit_U2ctypes();
  yInit_osek();
  xInsertIdNode((xIdNode)&yBloR_z_App_Z0_Class2);
  xInsertIdNode((xIdNode)&yPrsR_z_App_Z0T0_implicit_process_0);
  xInsertIdNode((xIdNode)&ySigR_z_App_Z0T0_implicit_process_0);
  xInsertIdNode((xIdNode)&yPrdR_z_App_Z0T0O0_find);
  xInsertIdNode((xIdNode)&yStaR_z_App_Z0T0O0E0_waiting);
  xInsertIdNode((xIdNode)&yStaR_z_App_Z0T0E0_waitOsek);
}
