
/* Coder .c file for system Class1 */
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#include "coderucf.h"
#include "Class1.ifc"
#include "Class1_cod.h"
#ifdef CODERINFO
#include "coderinfo.h"
#endif

/* *** SignalId *** */
tSDLTypeInfo ySDL_SignalId = {type_SDL_SignalId, 0, 0 T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("SignalId")};
