
/* Coder .c file for system Class2 */
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#include "coderucf.h"
#include "Class2.ifc"
#include "Class2_cod.h"
#ifdef CODERINFO
#include "coderinfo.h"
#endif

/* *** SignalId *** */
tSDLTypeInfo ySDL_SignalId = {type_SDL_SignalId, 0, 0 T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("SignalId")};

/* *** SIGNAL response *** */
tSDLSignalInfo ySDL_sig_response = {type_SDL_Signal, 0,
  (xptrint)sizeof(XSIGNALHEADERTYPE) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_Signal_SDL_Names("response"), 0, 0};

/* *** List of signals *** */
tSDLSignalInfo * xSignalList[] = {&ySDL_sig_response, 0};
xSignalIdNode xSignalIdList[] = {&ySigR_z_osek_I0_response, 0};
