
/* Coder .h file for system Class2 */
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC


extern tSDLTypeInfo ySDL_SignalId;
extern tSDLSignalInfo ySDL_sig_response;

extern tSDLSignalInfo * xSignalList[];
extern xSignalIdNode xSignalIdList[];
