
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ExtraOps.h"
#include "U2ctypes.h"
#include "osek.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "Class2.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "osek.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE osek
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#qncAcEy-gblLR3IYQLtk1RJE|pos(1,9)")
******/
XCONST struct xPackageIdStruct yPacR_z_osek__osek = {xPackageEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "osek" xIdNumber(0) XCOMMON_EXTRAS
  xIdNames(0) XPAC_EXTRAS};

/*****
* PROCESS TYPE Class1
* <<PACKAGE osek>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#mhocSLnd7cSLV0eY7EFyCJ7I|pos(1,18)")
******/
#ifdef XCOVERAGE
long int yPrsC_z_osek_T0_Class1[ySym_z_osek_T0_Class1+1];
#endif
XCONST XSIGTYPE yPrsS_z_osek_T0_Class1[] = {SIGNAL_NAME(pCALL_response,
  &ySigR_pCALL_z_osek_I0_response), (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z_osek_T0_Class1[] = {&xStartStateIdRec,
  &yStaR_z_osek_T0E0_waiting};
static xIdNode yPrsO_z_osek_T0_Class1[] = {(xIdNode)0, (xIdNode)0};
static XPRSNODE yPrsA_z_osek_T0_Class1 = (XPRSNODE)0;
static XPRSNODE yPrsB_z_osek_T0_Class1 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z_osek_T0_Class1 = {xProcessTypeEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_osek__osek, "Class1" xIdNumber(0)
  XCOMMON_EXTRAS, yPrsT_z_osek_T0_Class1, yPrsS_z_osek_T0_Class1 xOptChan(
  yPrsO_z_osek_T0_Class1), &ySigR_z_osek_T0_Class1, -1 xNrInst(1), 0,
  &yPrsB_z_osek_T0_Class1, (xptrint)sizeof(yVDef_z_osek_T0_Class1)
  xPrsPrioPar(xDefaultPrioProcess), &yPrsA_z_osek_T0_Class1 xTrace(-1)
  xGRTrace(-1) xBreakB(yRef_z_osek_T0_Class1) xBreakB(ySym_z_osek_T0_Class1)
  xBreakB(1) xMSCETrace(-1) xCoverage(yPrsC_z_osek_T0_Class1) xCoverage(0)
  xCoverage(0), yPAD_z_osek_T0_Class1, yFree_z_osek_T0_Class1,
  yIni_z_osek_T0_Class1, (xPrsIdNode)0, (xPrdIdNode *)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#mhocSLnd7cSLV0eY7EFyCJ7I|pos(1,18)\")")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z_osek_T0_Class1)};
static xSignalNode ySigA_z_osek_T0_Class1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_osek_T0_Class1 = {xStartUpSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_osek__osek
  xIdNames("-") xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(ySignalPar_z_osek_T0_Class1), &ySigA_z_osek_T0_Class1, 0
  xFreS(0) SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#mhocSLnd7cSLV0eY7EFyCJ7I|pos(1,18)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XPROCESSDEF_C(Class1,"Class1",z_osek_T0_Class1,yPAD_z_osek_T0_Class1,
  yVDef_z_osek_T0_Class1)
void yFree_z_osek_T0_Class1(void *yVarP)
{
}
void yIni_z_osek_T0_Class1(xPrsNode VarP)
{
  yVDef_z_osek_T0_Class1 *yVarP = (yVDef_z_osek_T0_Class1 *)VarP;
}

/*+++++
* GR ref function for process Class1
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#mhocSLnd7cSLV0eY7EFyCJ7I|pos(1,24)")
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z_osek_T0_Class1 (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#hdr57ILPUiiLXN-bnEnX4LwE|pos(1,9)\")";
    case 1: *SymbolType = xspCALLInput;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 2: *SymbolType = xspREPLYOutput;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 3: *SymbolType = xsNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#YrFKHL8jZdeLCFccyIRMcpmI|pos(1,13)\")";
    case 4: *SymbolType = xspCALLProcedureCall;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 5: *SymbolType = xspCALLNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process Class1
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#mhocSLnd7cSLV0eY7EFyCJ7I|pos(1,24)")
++++++*/
YPAD_FUNCTION(yPAD_z_osek_T0_Class1)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z_osek_T0_Class1)
  YPAD_TEMP_VARS
  YPRSNAME_VAR("Class1")

  BEGIN_PAD(yVDef_z_osek_T0_Class1)
#ifndef XNOPROCATSTARTUP
  {
    xPrdNode ActivePrd;
    ActivePrd = xGetActivePrd((xPrsNode)yVarP);
    while (ActivePrd != 0) {
#ifdef XVALIDATOR_LIB
      if ((*ActivePrd->RestartPRD)(VarP, ndstate)) {
#else
      if ((*ActivePrd->RestartPRD)(VarP)) {
#endif
        return;
      }
      ActivePrd = xGetActivePrd((xPrsNode)yVarP);
#ifdef XBREAKBEFORE
      if (ActivePrd != 0) {
        XBETWEEN_SYMBOLS(ActivePrd->RestartAddress, 133)
      } else {
        XBETWEEN_SYMBOLS(yVarP->RestartAddress,  135)
      }
#endif
    }
  }
#endif

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#hdr57ILPUiiLXN-bnEnX4LwE|pos(1,9)") */
  case 0:
    BEGIN_START_TRANSITION(ySignalPar_z_osek_T0_Class1)
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS(3, 150)

/* ----- NEXTSTATE waiting ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#YrFKHL8jZdeLCFccyIRMcpmI|pos(1,13)") */
#ifdef XCASELABELS
  case 3:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(waiting, z_osek_T0E0_waiting, "waiting")

/*-----
* Implicit INPUT pCALL_response
------*/
  case 1:
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("pCALL_response")
    XRPC_SAVE_SENDER
    ALLOC_REPLY_SIGNAL(pREPLY_response, ySigN_pREPLY_z_osek_I0_response,
      XRPC_SENDER_IN_ALLOC, XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    XBETWEEN_SYMBOLS(4, 170)

/*-----
* Implicit CALL (RPC) response
------*/
#ifdef XCASELABELS
  case 4:
#endif
    ALLOC_PROCEDURE(z_osek_T0O0_exported_procedure_response,
      yPrdN_z_osek_T0O0_exported_procedure_response,
      sizeof(yVDef_z_osek_T0O0_exported_procedure_response))
    PROCEDURE_ALLOC_ERROR
    CALL_PROCEDURE(z_osek_T0O0_exported_procedure_response,
      yPrdN_z_osek_T0O0_exported_procedure_response, 0, 2)
    PROCEDURE_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(2, 185)

/*-----
* Implicit OUTPUT pREPLY_response
------*/
#ifdef XCASEAFTERPRDLABELS
  case 2:
#endif
    SDL_2OUTPUT_RPC_REPLY(xDefaultPrioSignal, (xIdNode *)0, pREPLY_response,
      ySigN_pREPLY_z_osek_I0_response, XRPC_SENDER_IN_OUTPUT, 0,
      "pREPLY_response")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(5, 197)

/*-----
* Implicit NEXTSTATE -
------*/
#ifdef XCASELABELS
  case 5:
#endif
    SDL_DASH_NEXTSTATE
  default : return;
  }
}
static XCONST xInputAction yStaH_z_osek_T0_Asterisk[] = {xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z_osek_T0_Asterisk[] = {1, 0};
#ifdef XCOVERAGE
static long int yStaC_z_osek_T0_Asterisk[1+1];
#endif
XCONST struct xStateIdStruct yStaR_z_osek_T0_Asterisk = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z_osek_T0_Class1, "" xIdNumber(0) XCOMMON_EXTRAS,
  -1, yStaH_z_osek_T0_Asterisk,  yStaI_z_osek_T0_Asterisk, 0, 0,
  0 xCoverage(yStaC_z_osek_T0_Asterisk), (xStateIdNode)0 xBreakB("")
  XSTA_EXTRAS};

/*****
* STATE waiting
* <<PACKAGE osek/PROCESS TYPE Class1>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#KoCcuLAQ6dDLIXvjwEHVlnoL|pos(1,15)")
******/
static XCONST xInputAction yStaH_z_osek_T0E0_waiting[] = {xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z_osek_T0E0_waiting[] = {1, 0};
#ifdef XCOVERAGE
static long int yStaC_z_osek_T0E0_waiting[1+1];
#endif
XCONST struct xStateIdStruct yStaR_z_osek_T0E0_waiting = {xStateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z_osek_T0_Class1,
  "waiting" xIdNumber(0) XCOMMON_EXTRAS, z_osek_T0E0_waiting,
  yStaH_z_osek_T0E0_waiting, yStaI_z_osek_T0E0_waiting, 0, 0, 0
  xCoverage(yStaC_z_osek_T0E0_waiting), (xStateIdNode)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#KoCcuLAQ6dDLIXvjwEHVlnoL|pos(1,15)\")")
  XSTA_EXTRAS};

/*****
* PROCEDURE response
* <<PACKAGE osek/PROCESS TYPE Class1>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,40)")
******/
#ifdef XCOVERAGE
long int yPrdC_z_osek_T0O0_exported_procedure_response[ySym_z_osek_T0O0_exported_procedure_response+1];
#endif
static XCONST xStateIdNode yPrdT_z_osek_T0O0_exported_procedure_response[] =
  {&xStartStateIdRec, &yStaR_z_osek_T0O0E0_w};
static xPrdNode yPrdA_z_osek_T0O0_exported_procedure_response = (xPrdNode)0;
XCONST struct xPrdIdStruct yPrdR_z_osek_T0O0_exported_procedure_response =
  {xProcedureEC , (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z_osek_T0_Class1,
  "response" xIdNumber(0) XCOMMON_EXTRAS,
  yPrdT_z_osek_T0O0_exported_procedure_response, yPrsS_z_osek_T0_Class1,
  z_osek_T0O0_exported_procedure_response,
  yFree_z_osek_T0O0_exported_procedure_response,
  (xptrint)sizeof(yVDef_z_osek_T0O0_exported_procedure_response),
  &yPrdA_z_osek_T0O0_exported_procedure_response
  xBreakB(yRef_z_osek_T0O0_exported_procedure_response)
  xBreakB(ySym_z_osek_T0O0_exported_procedure_response) xBreakB(1)
  xCoverage(yPrdC_z_osek_T0O0_exported_procedure_response), (xPrdIdNode)0,
  (xPrdIdNode *)0 XPRD_EXTRAS};
void yFree_z_osek_T0O0_exported_procedure_response(void *yVarP)
{
}

/*+++++
* GR ref function for procedure response
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,90)")
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z_osek_T0O0_exported_procedure_response (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#CCfFCEaSSqiL5AihhL7*zh2V|pos(1,13)\")";
    case 1: *SymbolType = xspCALLInput;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 2: *SymbolType = xspREPLYOutput;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 3: *SymbolType = xsNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#lmp86L7bBalL4OHgsIfBQmxV|pos(1,17)\")";
    case 4: *SymbolType = xspCALLProcedureCall;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    case 5: *SymbolType = xspCALLNextstate;
      return "#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,9)\")";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for procedure response
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,90)")
++++++*/
YPRD_FUNCTION(z_osek_T0O0_exported_procedure_response)
{
  YPAD_YSVARP
  YPRD_YVARP(yVDef_z_osek_T0_Class1)
  yVDef_z_osek_T0O0_exported_procedure_response * yPrdVarP;
  YPRD_TEMP_VARS
  YPRDNAME_VAR("response")
    yPrdVarP =
    (yVDef_z_osek_T0O0_exported_procedure_response *)xGetActivePrd((xPrsNode)yVarP);

  LOOP_LABEL_PRD
  switch (yPrdVarP->RestartAddress) {

/* ----- START ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#CCfFCEaSSqiL5AihhL7*zh2V|pos(1,13)") */
  case 0:
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS_PRD(3, 311)

/* ----- NEXTSTATE w ----- */
/* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#lmp86L7bBalL4OHgsIfBQmxV|pos(1,17)") */
#ifdef XCASELABELS
  case 3:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE_PRD(w, z_osek_T0O0E0_w, "w")

/*-----
* Implicit INPUT pCALL_response
------*/
  case 1:
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("pCALL_response")
    XRPC_SAVE_SENDER_PRD
    ALLOC_REPLY_SIGNAL_PRD(pREPLY_response, ySigN_pREPLY_z_osek_I0_response,
      XRPC_SENDER_IN_ALLOC_PRD, XSIGNALHEADERTYPE)
    SIGNAL_ALLOC_ERROR
    XBETWEEN_SYMBOLS_PRD(4, 331)

/*-----
* Implicit CALL (RPC) response
------*/
#ifdef XCASELABELS
  case 4:
#endif
    ALLOC_PROCEDURE(z_osek_T0O0_exported_procedure_response,
      yPrdN_z_osek_T0O0_exported_procedure_response,
      sizeof(yVDef_z_osek_T0O0_exported_procedure_response))
    PROCEDURE_ALLOC_ERROR
    CALL_PROCEDURE_IN_PRD(z_osek_T0O0_exported_procedure_response,
      yPrdN_z_osek_T0O0_exported_procedure_response, 0, 2)
    PROCEDURE_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS_PRD(2, 346)

/*-----
* Implicit OUTPUT pREPLY_response
------*/
#ifdef XCASEAFTERPRDLABELS
  case 2:
#endif
    SDL_2OUTPUT_RPC_REPLY_PRD(xDefaultPrioSignal, (xIdNode *)0,
      pREPLY_response, ySigN_pREPLY_z_osek_I0_response,
      XRPC_SENDER_IN_OUTPUT_PRD, 0, "pREPLY_response")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS_PRD(5, 358)

/*-----
* Implicit NEXTSTATE -
------*/
#ifdef XCASELABELS
  case 5:
#endif
    SDL_DASH_NEXTSTATE_PRD
  }
  XEND_PRD
}

/*****
* STATE w
* <<PACKAGE osek/PROCESS TYPE Class1/PROCEDURE response>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#hdpcUVaVgrALkG8aHVLtzR1V|pos(1,19)")
******/
static XCONST xInputAction yStaH_z_osek_T0O0E0_w[] = {xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z_osek_T0O0E0_w[] = {1, 0};
#ifdef XCOVERAGE
static long int yStaC_z_osek_T0O0E0_w[1+1];
#endif
XCONST struct xStateIdStruct yStaR_z_osek_T0O0E0_w = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrdR_z_osek_T0O0_exported_procedure_response,
  "w" xIdNumber(0) XCOMMON_EXTRAS, z_osek_T0O0E0_w, yStaH_z_osek_T0O0E0_w,
  yStaI_z_osek_T0O0E0_w, 0, 0, 0 xCoverage(yStaC_z_osek_T0O0E0_w),
  (xStateIdNode)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#hdpcUVaVgrALkG8aHVLtzR1V|pos(1,19)\")")
  XSTA_EXTRAS};

/*****
* REMOTE PROCEDURE response
* <<PACKAGE osek>>
* #SDTREF(U2,"u2:C:\Documents and Settings\Other\Мои документы\My Projects\OSEK\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,22)")
******/
struct xRemotePrdIdStruct yRePR_z_osek_I0_response =  {xRemotePrdEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_osek__osek, "response" xIdNumber(0)
  XCOMMON_EXTRAS, 0};
XCONST struct xSignalIdStruct ySigR_pCALL_z_osek_I0_response = {xRPCSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_osek__osek,
  "pCALL_response" xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(SN_pCALL_response)
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,22)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
XCONST struct xSignalIdStruct ySigR_pREPLY_z_osek_I0_response = {xRPCSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_osek__osek,
  "pREPLY_response" xIdNumber(0) XCOMMON_EXTRAS,
  (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0) SIGCODE(SN_pREPLY_response)
  xBreakB("#SDTREF(U2,\"u2:C:\\Documents and Settings\\Other\\Мои документы\\My Projects\\OSEK\\osek.u2#SjuwFEQJ9kiLSb0ZYIGEp3qV|pos(1,22)\")")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_osek (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_osek__osek);
  yInit_U2ExtraOps();
  yInit_U2ctypes();
  xInsertIdNode((xIdNode)&yPrsR_z_osek_T0_Class1);
  xInsertIdNode((xIdNode)&ySigR_z_osek_T0_Class1);
  xInsertIdNode((xIdNode)&yPrdR_z_osek_T0O0_exported_procedure_response);
  xInsertIdNode((xIdNode)&yStaR_z_osek_T0O0E0_w);
  xInsertIdNode((xIdNode)&yStaR_z_osek_T0E0_waiting);
  xInsertIdNode((xIdNode)&yRePR_z_osek_I0_response);
  xInsertIdNode((xIdNode)&ySigR_pCALL_z_osek_I0_response);
  xInsertIdNode((xIdNode)&ySigR_pREPLY_z_osek_I0_response);
}
