
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#ifndef XX_U2ExtraOps_H
#define XX_U2ExtraOps_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE U2ExtraOps
* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\u2ExtraOps.pr",8,9)
******/
extern XCONST struct xPackageIdStruct yPacR_z_U2ExtraOps__U2ExtraOps;

extern void yInit_U2ExtraOps (void);

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(TEXT,"C:\\Program Files\\IBM\\Rational\\TAU\\4.3\\addins\\sdlkernels\\ADT\\u2ExtraOps.pr",766,1) */

#ifdef XSCT_CMICRO

#if (CFG_MAX_INSTANCES > 1)
  #define INSTANCE_VAR(INST)  \
    ((xInstanceData *)((char *)PartData->InstanceData + PartData->DataLength*(INST)))
#else
  #define INSTANCE_VAR(INST)  (PartData->InstanceData)
#endif
extern SDL_Integer z_U2ExtraOps_H0O0_numberactive(int);
extern SDL_PId z_U2ExtraOps_H0O2_getpid(int, SDL_Integer);
#define z_U2ExtraOps_H0O1_numberactive2 z_U2ExtraOps_H0O0_numberactive
#define z_U2ExtraOps_H0O3_getpid2 z_U2ExtraOps_H0O2_getpid
#define z_U2ExtraOps_H0O4_getpidbl ERROR_too_complex_for_agilec
#define z_U2ExtraOps_H0O5_getpidbl2 z_U2ExtraOps_H0O2_getpid
#define z_U2ExtraOps_H0O6_isa(P1,P2)  ERROR_isa_not_supported_in_AgileC;
#define z_U2ExtraOps_H0O7_asa(P1,P2)  ERROR_asa_not_supported_in_AgileC;
#define z_U2ExtraOps_H0O8_appendpid(P1,P2)   ERROR_appendpid_not_supported_in_AgileC;
#define z_U2ExtraOps_H0O9_appendpid2(P1,P2)  ERROR_appendpid_not_supported_in_AgileC;
#define z_U2ExtraOps_H0OA_removepid(P1,P2)   ERROR_removepid_not_supported_in_AgileC;
#define z_U2ExtraOps_H0OB_removepid2(P1,P2)  ERROR_removepid_not_supported_in_AgileC;
#define z_U2ExtraOps_H0OC_removepidvalue(P1,P2)   ERROR_removepidvalue_not_supported_in_AgileC;
#define z_U2ExtraOps_H0OD_removepidvalue2(P1,P2)  ERROR_removepidvalue_not_supported_in_AgileC;
#define U2ExtraOpsPARA(P1,P2) xPartNo_##P2
#define U2ExtraOpsPARA2(P1) xPartNo_##P1
#define U2ExtraOpsBLPARA2(P1) xPartNo_##P1

#else   COMMENT(( #ifdef XSCT_CMICRO ))

extern SDL_Integer z_U2ExtraOps_H0O0_numberactive(xIdNode, int, xPrsNode);
extern SDL_Integer z_U2ExtraOps_H0O1_numberactive2(xIdNode);
extern SDL_PId z_U2ExtraOps_H0O2_getpid(xIdNode, int, xPrsNode, SDL_Integer);
extern SDL_PId z_U2ExtraOps_H0O3_getpid2(xIdNode, SDL_Integer);
extern SDL_PId z_U2ExtraOps_H0O4_getpidbl(xPrsNode, xIdNode, ...);
extern SDL_PId z_U2ExtraOps_H0O5_getpidbl2(xIdNode, SDL_Integer);
extern SDL_Boolean z_U2ExtraOps_H0O6_isa(SDL_Pid, xPrsIdNode);
#define z_U2ExtraOps_H0O7_asa(PI,PT)   (z_U2ExtraOps_H0O6_isa(PI,PT) ? PI : SDL_NULL)
extern void z_U2ExtraOps_H0O8_appendpid(SDL_Pid, xIdNode, int, xPrsNode);
extern void z_U2ExtraOps_H0O9_appendpid2(SDL_Pid, xIdNode);
extern void z_U2ExtraOps_H0OA_removepid(xIdNode, int, xPrsNode, SDL_Integer);
extern void z_U2ExtraOps_H0OB_removepid2(xIdNode, SDL_Integer);
extern void z_U2ExtraOps_H0OC_removepidvalue(xIdNode, int, xPrsNode, SDL_Pid);
extern void z_U2ExtraOps_H0OD_removepidvalue2(xIdNode, SDL_Pid);
#define U2ExtraOpsPARA(P1,P2) P1,yPrsE_##P2,VarP
#define U2ExtraOpsPARA2(P1) (xIdNode)yPrsN_##P1
#define U2ExtraOpsBLPARA2(P1) (xIdNode)&yBloR_##P1

#endif   COMMENT(( #ifdef XSCT_CMICRO #else ))


#endif
