
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "U2ExtraOps.h"
#include "U2ctypes.h"
#include "MainApplicationPackage.h"
#ifdef XUSE_SIGNAL_NUMBERS
#include "Main.hs"
#endif
XSYSTEMVARS
#ifdef XCTRACE
static char  xFileName[] = "Main.c";
#endif

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* BLOCK INST Main
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#714hgIhDJoFLC1GZbEoEJVhV|pos(1,8)")
******/
extern XCONST struct xBlockIdStruct yBloR_z_Main;
extern XCONST xIdNode yBloP_z_Main[];

/*****
* GATE @implicit_port_2
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#0ScP7EhON7VLP9xgvVbSUB3L|pos(1,14)")
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z0_implicit_port_2[];
extern XCONST xIdNode yChaOR_z0_implicit_port_2[];
extern XCONST struct xChannelIdStruct yChaR_z0_implicit_port_2;
extern XCONST struct xChannelIdStruct yChaRR_z0_implicit_port_2;
#define yChaN_z0_implicit_port_2  (&yChaR_z0_implicit_port_2)
#endif

/*****
* PROCESS INST O
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#TEvGKIhdW75LKzQgwEH4-zZE|pos(1,17)")
******/
extern XCONST struct xPrsIdStruct yPrsR_z1_O;
#define yPrsN_z1_O  (&yPrsR_z1_O)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z1_O[];
#endif

/*****
* GATE @implicit_port_0
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main/PROCESS O>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#GwgUwLus39CLSW0YYInH2h-V|pos(1,14)")
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z10_implicit_port_0[];
extern XCONST xIdNode yChaOR_z10_implicit_port_0[];
extern XCONST struct xChannelIdStruct yChaR_z10_implicit_port_0;
extern XCONST struct xChannelIdStruct yChaRR_z10_implicit_port_0;
#define yChaN_z10_implicit_port_0  (&yChaR_z10_implicit_port_0)
#endif

/*****
* PROCESS INST @part__@implicit_process_0
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#0d--iE-oh1iLkDAcZEuFSvRE|pos(1,17)")
******/
extern XCONST struct xPrsIdStruct yPrsR_z2_part__implicit_process_0;
#define yPrsN_z2_part__implicit_process_0  (&yPrsR_z2_part__implicit_process_0)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z2_part__implicit_process_0[];
#endif

/*****
* GATE @implicit_port_1
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main
*     /PROCESS @part__@implicit_process_0>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#DPXeXEzoRlvLg6wkxIMLZlVL|pos(1,18)")
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z20_implicit_port_1[];
extern XCONST xIdNode yChaOR_z20_implicit_port_1[];
extern XCONST struct xChannelIdStruct yChaR_z20_implicit_port_1;
extern XCONST struct xChannelIdStruct yChaRR_z20_implicit_port_1;
#define yChaN_z20_implicit_port_1  (&yChaR_z20_implicit_port_1)
#endif

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* ENV
******/
#ifndef XMULTIPLESYSTEMS
#ifndef XOPTCHAN
xIdNode yEnvO_env[] = {(xIdNode)&yChaR_z0_implicit_port_2,
  (xIdNode)0  XTRACHANNELLIST};
#endif
#endif

/*****
* BLOCK INST Main
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#714hgIhDJoFLC1GZbEoEJVhV|pos(1,8)")
******/
XCONST xIdNode yBloP_z_Main[] = {(xIdNode)&yPrsR_z1_O,
  (xIdNode)&yPrsR_z2_part__implicit_process_0,
  xOptChanZ((xIdNode)&yChaRR_z0_implicit_port_2)};
static struct xBlockStruct yBloA_z_Main = {&yBloA_z_Main, &yBloA_z_Main,
  (xBlockNode)&yBloR_z_Main xNrInst(0), -1};
XCONST struct xBlockIdStruct yBloR_z_Main = {xBlockEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&xSymbolTableIdRec, "Main" xIdNumber(0) XCOMMON_EXTRAS,
  &yBloR_z_MainApplicationPackage_Z0_Main, yBloP_z_Main, (xPrdIdNode *)0,
  (xViewListRec *)0, (xViewIndexRec *)0 xNrInst(1), 1, &yBloA_z_Main,
  &yPrsR_z2_part__implicit_process_0 xTrace(-1) xMSCETrace(-1) xGRTrace(-1)
  xMSCETrace(0) XBLO_EXTRAS};

/*****
* GATE @implicit_port_2
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#0ScP7EhON7VLP9xgvVbSUB3L|pos(1,14)")
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z0_implicit_port_2[] = {SIGNAL_NAME(pREPLY_oppp,
  &ySigR_pREPLY_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z0_implicit_port_2[] = {SIGNAL_NAME(pCALL_oppp,
  &ySigR_pCALL_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
XCONST xIdNode yChaO_z0_implicit_port_2[] =
  {(xIdNode)&yChaR_z10_implicit_port_0, (xIdNode)&yChaR_z20_implicit_port_1,
  (xIdNode)0};
XCONST xIdNode yChaOR_z0_implicit_port_2[] = {(xIdNode)&yEnvR_env, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z0_implicit_port_2 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yBloR_z_Main,
  "@implicit_port_2" xIdNumber(0) XCOMMON_EXTRAS, yChaS_z0_implicit_port_2,
  yChaO_z0_implicit_port_2, &yChaRR_z0_implicit_port_2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z0_implicit_port_2 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yBloR_z_Main,
  "@implicit_port_2" xIdNumber(0) XCOMMON_EXTRAS, yChaSR_z0_implicit_port_2,
  yChaOR_z0_implicit_port_2, &yChaR_z0_implicit_port_2 XCHA_EXTRAS};
#endif

/*****
* PROCESS INST O
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#TEvGKIhdW75LKzQgwEH4-zZE|pos(1,17)")
******/
static XPRSNODE yPrsB_z1_O = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z1_O = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z_Main, "O" xIdNumber(0) XCOMMON_EXTRAS,
  yPrsT_z_MainApplicationPackage_T0_OS, yPrsS_z_MainApplicationPackage_T0_OS
  xOptChan(yPrsO_z1_O), 0, -1 xNrInst(1), 1, &yPrsB_z1_O,
  (xptrint)sizeof(yVDef_z_MainApplicationPackage_T0_OS)
  xPrsPrioPar(xDefaultPrioProcess), (XPRSNODE *)0 xTrace(-1) xGRTrace(-1)
  xBreakB(yRef_z_MainApplicationPackage_T0_OS)
  xBreakB(ySym_z_MainApplicationPackage_T0_OS) xBreakB(1) xMSCETrace(-1)
  xCoverage(yPrsC_z_MainApplicationPackage_T0_OS) xCoverage(0) xCoverage(0), 0,
  0, 0, &yPrsR_z_MainApplicationPackage_T0_OS, (xPrdIdNode *)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Users\\evgeny\\Documents\\My Projects\\OS_model\\MainApplication.u2#TEvGKIhdW75LKzQgwEH4-zZE|pos(1,17)\")")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z_MainApplicationPackage_T0_OS)};
static struct xRemotePrdListStruct yPrdE1_z1_O =
  {(xRemotePrdListNode)0, &yPrsR_z1_O};
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z1_O[] = {(xIdNode)&yChaRR_z10_implicit_port_0,
  (xIdNode)0};
#endif

/*****
* GATE @implicit_port_0
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main/PROCESS O>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#GwgUwLus39CLSW0YYInH2h-V|pos(1,14)")
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z10_implicit_port_0[] = {SIGNAL_NAME(pCALL_oppp,
  &ySigR_pCALL_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z10_implicit_port_0[] = {SIGNAL_NAME(pREPLY_oppp,
  &ySigR_pREPLY_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
XCONST xIdNode yChaO_z10_implicit_port_0[] = {(xIdNode)&yPrsR_z1_O, (xIdNode)0};
XCONST xIdNode yChaOR_z10_implicit_port_0[] =
  {(xIdNode)&yChaRR_z0_implicit_port_2, (xIdNode)&yChaR_z20_implicit_port_1,
  (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z10_implicit_port_0 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z1_O, "@implicit_port_0" xIdNumber(0)
  XCOMMON_EXTRAS, yChaS_z10_implicit_port_0, yChaO_z10_implicit_port_0,
  &yChaRR_z10_implicit_port_0 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z10_implicit_port_0 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z1_O, "@implicit_port_0" xIdNumber(0)
  XCOMMON_EXTRAS, yChaSR_z10_implicit_port_0, yChaOR_z10_implicit_port_0,
  &yChaR_z10_implicit_port_0 XCHA_EXTRAS};
#endif

/*****
* PROCESS INST @part__@implicit_process_0
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#0d--iE-oh1iLkDAcZEuFSvRE|pos(1,17)")
******/
static XPRSNODE yPrsB_z2_part__implicit_process_0 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z2_part__implicit_process_0 = {xProcessEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yBloR_z_Main, "Main" xIdNumber(0)
  XCOMMON_EXTRAS, yPrsT_z_MainApplicationPackage_Z0T0_implicit_process_0,
  yPrsS_z_MainApplicationPackage_Z0T0_implicit_process_0 xOptChan(
  yPrsO_z2_part__implicit_process_0), 0, -1 xNrInst(1), 1,
  &yPrsB_z2_part__implicit_process_0,
  (xptrint)sizeof(yVDef_z_MainApplicationPackage_Z0T0_implicit_process_0)
  xPrsPrioPar(xDefaultPrioProcess), (XPRSNODE *)0 xTrace(-1) xGRTrace(-1)
  xBreakB(yRef_z_MainApplicationPackage_Z0T0_implicit_process_0)
  xBreakB(ySym_z_MainApplicationPackage_Z0T0_implicit_process_0) xBreakB(0)
  xMSCETrace(-1)
  xCoverage(yPrsC_z_MainApplicationPackage_Z0T0_implicit_process_0)
  xCoverage(0) xCoverage(0), 0, 0, 0,
  &yPrsR_z_MainApplicationPackage_Z0T0_implicit_process_0, (xPrdIdNode *)0
  xBreakB("#SDTREF(U2,\"u2:C:\\Users\\evgeny\\Documents\\My Projects\\OS_model\\MainApplication.u2#714hgIhDJoFLC1GZbEoEJVhV|pos(1,8)\")")
  xThreadName(0) xThreadName(0)
  XPRS_EXTRAS(z_MainApplicationPackage_Z0T0_implicit_process_0)};
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z2_part__implicit_process_0[] =
  {(xIdNode)&yChaRR_z20_implicit_port_1, (xIdNode)0};
#endif

/*****
* GATE @implicit_port_1
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main
*     /PROCESS @part__@implicit_process_0>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#DPXeXEzoRlvLg6wkxIMLZlVL|pos(1,18)")
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z20_implicit_port_1[] = {SIGNAL_NAME(pREPLY_oppp,
  &ySigR_pREPLY_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z20_implicit_port_1[] = {SIGNAL_NAME(pCALL_oppp,
  &ySigR_pCALL_z_MainApplicationPackage_I0_oppp), (XSIGTYPE)0};
XCONST xIdNode yChaO_z20_implicit_port_1[] =
  {(xIdNode)&yPrsR_z2_part__implicit_process_0, (xIdNode)0};
XCONST xIdNode yChaOR_z20_implicit_port_1[] =
  {(xIdNode)&yChaRR_z0_implicit_port_2, (xIdNode)&yChaR_z10_implicit_port_0,
  (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z20_implicit_port_1 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z2_part__implicit_process_0,
  "@implicit_port_1" xIdNumber(0) XCOMMON_EXTRAS, yChaS_z20_implicit_port_1,
  yChaO_z20_implicit_port_1, &yChaRR_z20_implicit_port_1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z20_implicit_port_1 = {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z2_part__implicit_process_0,
  "@implicit_port_1" xIdNumber(0) XCOMMON_EXTRAS, yChaSR_z20_implicit_port_1,
  yChaOR_z20_implicit_port_1, &yChaR_z20_implicit_port_1 XCHA_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
#ifndef XMULTIPLESYSTEMS
void yInit (void)
{
#else
void yInit_Main (void)
{
#endif
  int  Temp;
  YINIT_TEMP_VARS
  BEGIN_YINIT

#ifdef XMONITOR
  xTranslatorVersion =
    "Program generated by Cbasic 4.3.0.0.13660";
#endif
  yInit_U2ExtraOps();
  yInit_U2ctypes();
  yInit_MainApplicationPackage();
  xInsertIdNode((xIdNode)&yBloR_z_Main);
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z0_implicit_port_2);
  xInsertIdNode((xIdNode)&yChaRR_z0_implicit_port_2);
#endif
  xInsertIdNode((xIdNode)&yPrsR_z1_O);
  xInsertExportedPrd(&yPrdE1_z1_O, &yRePR_z_MainApplicationPackage_I0_oppp);
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z10_implicit_port_0);
  xInsertIdNode((xIdNode)&yChaRR_z10_implicit_port_0);
#endif
  xInsertIdNode((xIdNode)&yPrsR_z2_part__implicit_process_0);
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z20_implicit_port_1);
  xInsertIdNode((xIdNode)&yChaRR_z20_implicit_port_1);
#endif
}
