
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#ifndef XX_MainApplicationPackage_H
#define XX_MainApplicationPackage_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE MainApplicationPackage
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#*dMmOEwBTPALSmtgnIJJbPVE|pos(1,9)")
******/
extern XCONST struct xPackageIdStruct yPacR_z_MainApplicationPackage__MainApplicationPackage;

extern void yInit_MainApplicationPackage (void);

/*****
* BLOCK TYPE Main
* <<PACKAGE MainApplicationPackage>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#714hgIhDJoFLC1GZbEoEJVhV|pos(1,16)")
******/
extern XCONST struct xBlockIdStruct yBloR_z_MainApplicationPackage_Z0_Main;
#define yPrsE_z_MainApplicationPackage_Z0P0_O  0
#define yPrsE_z_MainApplicationPackage_Z0P1_part__implicit_process_0  1
#define yChaE_z_MainApplicationPackage_Z0G0_implicit_port_2  2

/*****
* PROCESS TYPE @implicit_process_0
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#0d--iE-oh1iLkDAcZEuFSvRE|pos(1,22)")
******/
extern XCONST XSIGTYPE yPrsS_z_MainApplicationPackage_Z0T0_implicit_process_0[];
extern XCONST xStateIdNode yPrsT_z_MainApplicationPackage_Z0T0_implicit_process_0[];
extern XCONST struct xPrsIdStruct yPrsR_z_MainApplicationPackage_Z0T0_implicit_process_0;
#define yPrsN_z_MainApplicationPackage_Z0T0_implicit_process_0  (&yPrsR_z_MainApplicationPackage_Z0T0_implicit_process_0)
#ifdef XCOVERAGE
extern long int yPrsC_z_MainApplicationPackage_Z0T0_implicit_process_0[];
#endif
YPAD_PROTOTYPE(yPAD_z_MainApplicationPackage_Z0T0_implicit_process_0)
extern XCONST struct xSignalIdStruct ySigR_z_MainApplicationPackage_Z0T0_implicit_process_0;
#define ySigN_z_MainApplicationPackage_Z0T0_implicit_process_0  (&ySigR_z_MainApplicationPackage_Z0T0_implicit_process_0)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} ySignalPar_z_MainApplicationPackage_Z0T0_implicit_process_0;
typedef ySignalPar_z_MainApplicationPackage_Z0T0_implicit_process_0  *yPDP_z_MainApplicationPackage_Z0T0_implicit_process_0;
XPROCESSDEF_H(implicit_process_0, \
  "implicit_process_0",z_MainApplicationPackage_Z0T0_implicit_process_0, \
  yPAD_z_MainApplicationPackage_Z0T0_implicit_process_0, \
  yVDef_z_MainApplicationPackage_Z0T0_implicit_process_0)
#define yChaE_z_MainApplicationPackage_Z0T0G0_implicit_port_1  0
#ifdef XBREAKBEFORE
#define ySym_z_MainApplicationPackage_Z0T0_implicit_process_0  4
extern char * yRef_z_MainApplicationPackage_Z0T0_implicit_process_0 (int, xSymbolType *);
#endif
typedef struct {
  PROCESS_VARS
} yVDef_z_MainApplicationPackage_Z0T0_implicit_process_0;
typedef yVDef_z_MainApplicationPackage_Z0T0_implicit_process_0  *yVDP_z_MainApplicationPackage_Z0T0_implicit_process_0;
extern void yFree_z_MainApplicationPackage_Z0T0_implicit_process_0 (void *);
extern void yIni_z_MainApplicationPackage_Z0T0_implicit_process_0 (xPrsNode);

/*****
* PROCEDURE op
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main
*     /PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#fbaNtEfxZVDLA8ia1El5WCSV|pos(1,23)")
******/
YPRD_PROTOTYPE(z_MainApplicationPackage_Z0T0O0_op)
extern XCONST struct xPrdIdStruct yPrdR_z_MainApplicationPackage_Z0T0O0_op;
#define yPrdN_z_MainApplicationPackage_Z0T0O0_op  (&yPrdR_z_MainApplicationPackage_Z0T0O0_op)
#ifdef XBREAKBEFORE
#define ySym_z_MainApplicationPackage_Z0T0O0_op  2
extern char * yRef_z_MainApplicationPackage_Z0T0O0_op (int, xSymbolType *);
#endif
typedef struct {
  PROCEDURE_VARS
} yVDef_z_MainApplicationPackage_Z0T0O0_op;
typedef yVDef_z_MainApplicationPackage_Z0T0O0_op  *yVDP_z_MainApplicationPackage_Z0T0O0_op;
extern void yFree_z_MainApplicationPackage_Z0T0O0_op (void *);

/*****
* STATE st
* <<PACKAGE MainApplicationPackage/BLOCK TYPE Main
*     /PROCESS TYPE @implicit_process_0>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#zLJmuLMb565LyiTjqLumy8xE|pos(1,19)")
******/
#define z_MainApplicationPackage_Z0T0E0_st  1
extern XCONST struct xStateIdStruct yStaR_z_MainApplicationPackage_Z0T0E0_st;
#define yStaN_z_MainApplicationPackage_Z0T0E0_st  (&yStaR_z_MainApplicationPackage_Z0T0E0_st)

/*****
* PROCESS TYPE OS
* <<PACKAGE MainApplicationPackage>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#m3INILyJJYSLx3akAE1Wqy8E|pos(1,18)")
******/
extern XCONST XSIGTYPE yPrsS_z_MainApplicationPackage_T0_OS[];
extern XCONST xStateIdNode yPrsT_z_MainApplicationPackage_T0_OS[];
extern XCONST struct xPrsIdStruct yPrsR_z_MainApplicationPackage_T0_OS;
#define yPrsN_z_MainApplicationPackage_T0_OS  (&yPrsR_z_MainApplicationPackage_T0_OS)
#ifdef XCOVERAGE
extern long int yPrsC_z_MainApplicationPackage_T0_OS[];
#endif
YPAD_PROTOTYPE(yPAD_z_MainApplicationPackage_T0_OS)
extern XCONST struct xSignalIdStruct ySigR_z_MainApplicationPackage_T0_OS;
#define ySigN_z_MainApplicationPackage_T0_OS  (&ySigR_z_MainApplicationPackage_T0_OS)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} ySignalPar_z_MainApplicationPackage_T0_OS;
typedef ySignalPar_z_MainApplicationPackage_T0_OS  *yPDP_z_MainApplicationPackage_T0_OS;
XPROCESSDEF_H(OS,"OS",z_MainApplicationPackage_T0_OS, \
  yPAD_z_MainApplicationPackage_T0_OS,yVDef_z_MainApplicationPackage_T0_OS)
#define yChaE_z_MainApplicationPackage_T0G0_implicit_port_0  0
#ifdef XBREAKBEFORE
#define ySym_z_MainApplicationPackage_T0_OS  5
extern char * yRef_z_MainApplicationPackage_T0_OS (int, xSymbolType *);
#endif
typedef struct {
  PROCESS_VARS
} yVDef_z_MainApplicationPackage_T0_OS;
typedef yVDef_z_MainApplicationPackage_T0_OS  *yVDP_z_MainApplicationPackage_T0_OS;
extern void yFree_z_MainApplicationPackage_T0_OS (void *);
extern void yIni_z_MainApplicationPackage_T0_OS (xPrsNode);

extern XCONST struct xStateIdStruct yStaR_z_MainApplicationPackage_T0_Asterisk;
#define yStaN_z_MainApplicationPackage_T0_Asterisk  (&yStaR_z_MainApplicationPackage_T0_Asterisk)

/*****
* PROCEDURE oppp
* <<PACKAGE MainApplicationPackage/PROCESS TYPE OS>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#yW*q7EFQmOBLMGOfKVXZ0gPV|pos(1,36)")
******/
YPRD_PROTOTYPE(z_MainApplicationPackage_T0O0_exported_procedure_oppp)
extern XCONST struct xPrdIdStruct yPrdR_z_MainApplicationPackage_T0O0_exported_procedure_oppp;
#define yPrdN_z_MainApplicationPackage_T0O0_exported_procedure_oppp  (&yPrdR_z_MainApplicationPackage_T0O0_exported_procedure_oppp)
#ifdef XBREAKBEFORE
#define ySym_z_MainApplicationPackage_T0O0_exported_procedure_oppp  5
extern char * yRef_z_MainApplicationPackage_T0O0_exported_procedure_oppp (int, xSymbolType *);
#endif
typedef struct {
  PROCEDURE_VARS
} yVDef_z_MainApplicationPackage_T0O0_exported_procedure_oppp;
typedef yVDef_z_MainApplicationPackage_T0O0_exported_procedure_oppp  *yVDP_z_MainApplicationPackage_T0O0_exported_procedure_oppp;
extern void yFree_z_MainApplicationPackage_T0O0_exported_procedure_oppp (void *);

/*****
* STATE cc
* <<PACKAGE MainApplicationPackage/PROCESS TYPE OS
*     /PROCEDURE oppp>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#pGZKCIFXr5DL4eifbLJFQWwL|pos(1,19)")
******/
#define z_MainApplicationPackage_T0O0E0_cc  1
extern XCONST struct xStateIdStruct yStaR_z_MainApplicationPackage_T0O0E0_cc;
#define yStaN_z_MainApplicationPackage_T0O0E0_cc  (&yStaR_z_MainApplicationPackage_T0O0E0_cc)

/*****
* STATE wait_for_calls
* <<PACKAGE MainApplicationPackage/PROCESS TYPE OS>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#m3INILyJJYSLx3akAE1Wqy8E|pos(1,15)")
******/
#define z_MainApplicationPackage_T0E0_wait_for_calls  1
extern XCONST struct xStateIdStruct yStaR_z_MainApplicationPackage_T0E0_wait_for_calls;
#define yStaN_z_MainApplicationPackage_T0E0_wait_for_calls  (&yStaR_z_MainApplicationPackage_T0E0_wait_for_calls)

/*****
* REMOTE PROCEDURE oppp
* <<PACKAGE MainApplicationPackage>>
* #SDTREF(U2,"u2:C:\Users\evgeny\Documents\My Projects\OS_model\MainApplication.u2#yW*q7EFQmOBLMGOfKVXZ0gPV|pos(1,22)")
******/
extern struct xRemotePrdIdStruct yRePR_z_MainApplicationPackage_I0_oppp;
extern XCONST struct xSignalIdStruct ySigR_pCALL_z_MainApplicationPackage_I0_oppp;
extern XCONST struct xSignalIdStruct ySigR_pREPLY_z_MainApplicationPackage_I0_oppp;
#define ySigN_pCALL_z_MainApplicationPackage_I0_oppp  (&ySigR_pCALL_z_MainApplicationPackage_I0_oppp)
#define ySigN_pREPLY_z_MainApplicationPackage_I0_oppp  (&ySigR_pREPLY_z_MainApplicationPackage_I0_oppp)

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
