
/* Coder .h file for system Main */
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC


extern tSDLTypeInfo ySDL_SignalId;
extern tSDLSignalInfo ySDL_sig_oppp;

extern tSDLSignalInfo * xSignalList[];
extern xSignalIdNode xSignalIdList[];
