
/* Coder .c file for system Main */
/* Program generated by Cbasic 4.3.0.0.13660 */
#define XSCT_CBASIC

#define C_TRANSLATOR_4_1
#include "coderucf.h"
#include "Main.ifc"
#include "Main_cod.h"
#ifdef CODERINFO
#include "coderinfo.h"
#endif

/* *** SignalId *** */
tSDLTypeInfo ySDL_SignalId = {type_SDL_SignalId, 0, 0 T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("SignalId")};

/* *** SIGNAL oppp *** */
tSDLSignalInfo ySDL_sig_oppp = {type_SDL_Signal, 0,
  (xptrint)sizeof(XSIGNALHEADERTYPE) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_Signal_SDL_Names("oppp"), 0, 0};

/* *** List of signals *** */
tSDLSignalInfo * xSignalList[] = {&ySDL_sig_oppp, 0};
xSignalIdNode xSignalIdList[] = {&ySigR_z_MainApplicationPackage_I0_oppp, 0};
